/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RaidsRouteImport } from './routes/raids'
import { Route as MapRouteImport } from './routes/map'
import { Route as LootRouteImport } from './routes/loot'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HideoutRouteImport } from './routes/hideout'
import { Route as DiveRouteImport } from './routes/dive'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RaidDungeonIdRouteImport } from './routes/raid.$dungeonId'
import { Route as GridCatIdRouteImport } from './routes/grid.$catId'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RaidsRoute = RaidsRouteImport.update({
  id: '/raids',
  path: '/raids',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LootRoute = LootRouteImport.update({
  id: '/loot',
  path: '/loot',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HideoutRoute = HideoutRouteImport.update({
  id: '/hideout',
  path: '/hideout',
  getParentRoute: () => rootRouteImport,
} as any)
const DiveRoute = DiveRouteImport.update({
  id: '/dive',
  path: '/dive',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaidDungeonIdRoute = RaidDungeonIdRouteImport.update({
  id: '/raid/$dungeonId',
  path: '/raid/$dungeonId',
  getParentRoute: () => rootRouteImport,
} as any)
const GridCatIdRoute = GridCatIdRouteImport.update({
  id: '/grid/$catId',
  path: '/grid/$catId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/dive': typeof DiveRoute
  '/hideout': typeof HideoutRoute
  '/inventory': typeof InventoryRoute
  '/loot': typeof LootRoute
  '/map': typeof MapRoute
  '/raids': typeof RaidsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/grid/$catId': typeof GridCatIdRoute
  '/raid/$dungeonId': typeof RaidDungeonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/dive': typeof DiveRoute
  '/hideout': typeof HideoutRoute
  '/inventory': typeof InventoryRoute
  '/loot': typeof LootRoute
  '/map': typeof MapRoute
  '/raids': typeof RaidsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/grid/$catId': typeof GridCatIdRoute
  '/raid/$dungeonId': typeof RaidDungeonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/dive': typeof DiveRoute
  '/hideout': typeof HideoutRoute
  '/inventory': typeof InventoryRoute
  '/loot': typeof LootRoute
  '/map': typeof MapRoute
  '/raids': typeof RaidsRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/grid/$catId': typeof GridCatIdRoute
  '/raid/$dungeonId': typeof RaidDungeonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crew'
    | '/dive'
    | '/hideout'
    | '/inventory'
    | '/loot'
    | '/map'
    | '/raids'
    | '/shop'
    | '/story'
    | '/grid/$catId'
    | '/raid/$dungeonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crew'
    | '/dive'
    | '/hideout'
    | '/inventory'
    | '/loot'
    | '/map'
    | '/raids'
    | '/shop'
    | '/story'
    | '/grid/$catId'
    | '/raid/$dungeonId'
  id:
    | '__root__'
    | '/'
    | '/crew'
    | '/dive'
    | '/hideout'
    | '/inventory'
    | '/loot'
    | '/map'
    | '/raids'
    | '/shop'
    | '/story'
    | '/grid/$catId'
    | '/raid/$dungeonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrewRoute: typeof CrewRoute
  DiveRoute: typeof DiveRoute
  HideoutRoute: typeof HideoutRoute
  InventoryRoute: typeof InventoryRoute
  LootRoute: typeof LootRoute
  MapRoute: typeof MapRoute
  RaidsRoute: typeof RaidsRoute
  ShopRoute: typeof ShopRoute
  StoryRoute: typeof StoryRoute
  GridCatIdRoute: typeof GridCatIdRoute
  RaidDungeonIdRoute: typeof RaidDungeonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raids': {
      id: '/raids'
      path: '/raids'
      fullPath: '/raids'
      preLoaderRoute: typeof RaidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loot': {
      id: '/loot'
      path: '/loot'
      fullPath: '/loot'
      preLoaderRoute: typeof LootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hideout': {
      id: '/hideout'
      path: '/hideout'
      fullPath: '/hideout'
      preLoaderRoute: typeof HideoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dive': {
      id: '/dive'
      path: '/dive'
      fullPath: '/dive'
      preLoaderRoute: typeof DiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raid/$dungeonId': {
      id: '/raid/$dungeonId'
      path: '/raid/$dungeonId'
      fullPath: '/raid/$dungeonId'
      preLoaderRoute: typeof RaidDungeonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid/$catId': {
      id: '/grid/$catId'
      path: '/grid/$catId'
      fullPath: '/grid/$catId'
      preLoaderRoute: typeof GridCatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrewRoute: CrewRoute,
  DiveRoute: DiveRoute,
  HideoutRoute: HideoutRoute,
  InventoryRoute: InventoryRoute,
  LootRoute: LootRoute,
  MapRoute: MapRoute,
  RaidsRoute: RaidsRoute,
  ShopRoute: ShopRoute,
  StoryRoute: StoryRoute,
  GridCatIdRoute: GridCatIdRoute,
  RaidDungeonIdRoute: RaidDungeonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
